version: '3'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    restart: always
    networks:
      - project
    ports:
      - "5432:5432"

  pg_admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - project
    depends_on:
      - postgres

  backend:
    build: ./backend
    restart: always
    command: python main.py
    volumes:
      - ./backend:/usr/src/app
    networks:
      - project
    ports:
      - "8000:8000"

  redis:
    image: redis:7
    networks:
      - project
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    restart: always
    command: yarn start
    volumes:
      - ./frontend:/usr/src/frontend
    networks:
      - project
    ports:
      - "3000:3000"
networks:
  project:
