"""set raw book not null

Revision ID: 33bcf74dd53a
Revises: ebc284450ffd
Create Date: 2022-01-09 22:20:47.466284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33bcf74dd53a'
down_revision = 'ebc284450ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Books', 'raw',
               existing_type=mysql.LONGBLOB(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Books', 'raw',
               existing_type=mysql.LONGBLOB(),
               nullable=True)
    # ### end Alembic commands ###
