"""Update UserProgress model

Revision ID: 628f175daf0b
Revises: 722566665647
Create Date: 2022-01-07 21:59:08.830401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628f175daf0b'
down_revision = '722566665647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
