"""Unique users name

Revision ID: 722566665647
Revises: 1b1b1bd229a0
Create Date: 2022-01-07 14:16:54.137166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722566665647'
down_revision = '1b1b1bd229a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    # ### end Alembic commands ###
