"""Create Users table

Revision ID: b6e3e7776296
Revises: 5ab89b6ff420
Create Date: 2022-01-06 21:00:14.167560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e3e7776296'
down_revision = '5ab89b6ff420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Books', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Books', 'Users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Books', type_='foreignkey')
    op.drop_column('Books', 'user_id')
    # ### end Alembic commands ###
