"""Add raw field for Book

Revision ID: ebc284450ffd
Revises: 628f175daf0b
Create Date: 2022-01-08 02:37:02.604101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc284450ffd'
down_revision = '628f175daf0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Books', sa.Column('raw', sa.LargeBinary(length=1073741824), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Books', 'raw')
    # ### end Alembic commands ###
