"""Create many to many rel for user progress

Revision ID: 1b1b1bd229a0
Revises: b6e3e7776296
Create Date: 2022-01-07 13:41:31.895866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1b1bd229a0'
down_revision = 'b6e3e7776296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UsersProgress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['Books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'book_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UsersProgress')
    # ### end Alembic commands ###
